DRIVERPATH = $(ROOT)/drivers

include $(DRIVERPATH)/lsm6dsl/lsm6dsl.mk
include $(DRIVERPATH)/iis2mdc/iis2mdc.mk

DRIVERSRC = $(LSM6DSLSRC) $(IIS2MDCSRC)

DRIVERINC = $(LSM6DSLINC) $(IIS2MDCINC)

DRIVERTESTS = $(LSM6DSL_PATH)/test